# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
b = np.array([[1,2,3],
             [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
c = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
a, b, c

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a.ndim, a.shape, a.size, type(a), a.dtype

(1, (3,), 3, numpy.ndarray, dtype('int32'))

In [11]:
# Attributes of 2-dimensional array
b.shape, b.ndim, b.dtype, b.size, type(b)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [12]:
# Attributes of 3-dimensional array
c.shape, c.ndim, c.dtype, c.size, type(c)

((3, 3), 2, dtype('int32'), 9, numpy.ndarray)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(c)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [16]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# Create an array within a range of 0 and 100 with step 3
array_1 = np.arange(0, 100, 3)
array_1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_2 = np.random.randint(0, 10, size=(7, 2))
array_2

array([[0, 5],
       [8, 8],
       [1, 0],
       [6, 9],
       [6, 8],
       [5, 0],
       [0, 4]])

In [23]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_3 = np.random.random((3,5))
array_3

array([[0.77476113, 0.71634166, 0.33805277, 0.7391199 , 0.36923756],
       [0.8753605 , 0.55748141, 0.9850393 , 0.99528702, 0.43230106],
       [0.99301038, 0.80281686, 0.12832073, 0.07130865, 0.72984551]])

In [25]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array_4 = np.random.randint(0, 10, size=(4, 6))
array_4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [29]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array_5 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
array_5, np.unique(array_5)

(array([[9, 7, 9, 8, 2, 1, 7],
        [7, 8, 5, 3, 8, 6, 3],
        [1, 3, 5, 3, 1, 5, 7]]),
 array([1, 2, 3, 5, 6, 7, 8, 9]))

In [31]:
# Find the 0'th index of the latest array you created
array_5[0][0]

9

In [32]:
# Get the first 2 rows of latest array you created
array_5[:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [33]:
# Get the first 2 values of the first 2 rows of the latest array
array_5[:2, :2]

array([[9, 7],
       [7, 8]])

In [35]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a1 = np.random.randint(0, 10, size=(3, 5))
a2 = np.ones((3, 5))
a1, a2

(array([[5, 1, 9, 8, 4],
        [5, 3, 9, 6, 8],
        [6, 0, 0, 8, 8]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [36]:
# Add the two arrays together
a1 + a2

array([[ 6.,  2., 10.,  9.,  5.],
       [ 6.,  4., 10.,  7.,  9.],
       [ 7.,  1.,  1.,  9.,  9.]])

In [37]:
# Create another array of ones of shape (5, 3)
a3 = np.ones((5, 3))
a3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# Try add the array of ones and the other most recent array together
a1 + a3.T

array([[ 6.,  2., 10.,  9.,  5.],
       [ 6.,  4., 10.,  7.,  9.],
       [ 7.,  1.,  1.,  9.,  9.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [41]:
# Create another array of ones of shape (3, 5)
a4 = np.ones((3,5))

In [43]:
# Subtract the new array of ones from the other most recent array
a3 - a4.T

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
# Multiply the ones array with the latest array
a3 * a4.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
# Take the latest array to the power of 2 using '**'
a4 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
# Do the same thing with np.square()
np.square(a1)

array([[25,  1, 81, 64, 16],
       [25,  9, 81, 36, 64],
       [36,  0,  0, 64, 64]], dtype=int32)

In [50]:
# Find the mean of the latest array using np.mean()
a1.mean()

5.333333333333333

In [52]:
# Find the maximum of the latest array using np.max()
a1.max()

9

In [53]:
# Find the minimum of the latest array using np.min()
a1.min()

0

In [54]:
# Find the standard deviation of the latest array
np.std(a1)

3.0477678535099892

In [55]:
# Find the variance of the latest array
np.var(a1)

9.288888888888888

In [57]:
# Reshape the latest array to (3, 5, 1)
a6 = np.reshape(a1, (3, 5, 1))
a6

array([[[5],
        [1],
        [9],
        [8],
        [4]],

       [[5],
        [3],
        [9],
        [6],
        [8]],

       [[6],
        [0],
        [0],
        [8],
        [8]]])

In [58]:
# Transpose the latest array
a6.T

array([[[5, 5, 6],
        [1, 3, 0],
        [9, 9, 0],
        [8, 6, 8],
        [4, 8, 8]]])

What does the transpose do?

In [59]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
b1 = np.random.randint(0, 10, (3, 3))
b2 = np.random.randint(0, 10, (3, 2))

In [60]:
# Perform a dot product on the two newest arrays you created
b1.dot(b2)

array([[ 76,  83],
       [ 96, 135],
       [ 44,  92]])

In [61]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
b3 = np.random.randint(0,10, (4, 3))
b4 = np.random.randint(0, 10, (4, 3))

In [62]:
# Perform a dot product on the two newest arrays you created
b3.dot(b4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [63]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
b3.dot(b4.T)

array([[ 0,  3, 12,  6],
       [ 6, 60, 36, 45],
       [ 0, 11,  4,  4],
       [ 7, 46, 16, 36]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [64]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
c1 = np.random.randint(0,10, size=(5, 4))
c2 = np.random.randint(0, 10, size=(5,4))

In [65]:
# Compare the two arrays with '>'
c1 > c2

array([[ True, False,  True,  True],
       [ True,  True, False, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [ True, False, False,  True]])

What happens when you compare the arrays with `>`?

In [67]:
# Compare the two arrays with '>='
c1 >=c2

array([[ True, False,  True,  True],
       [ True,  True, False, False],
       [ True, False, False,  True],
       [False,  True, False,  True],
       [ True, False, False,  True]])

In [68]:
# Find which elements of the first array are greater than 7
c1 > 7

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [69]:
# Which parts of each array are equal? (try using '==')
c1 == c2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False, False]])

In [70]:
# Sort one of the arrays you just created in ascending order
np.sort(c1)

array([[3, 5, 6, 9],
       [0, 5, 6, 7],
       [1, 3, 4, 7],
       [0, 5, 5, 8],
       [2, 3, 3, 5]])

In [71]:
# Sort the indexes of one of the arrays you just created
np.argsort(c1)

array([[3, 1, 2, 0],
       [2, 3, 0, 1],
       [3, 2, 1, 0],
       [2, 0, 1, 3],
       [1, 2, 3, 0]], dtype=int64)

In [72]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(c1)

0

In [73]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(c1)

6

In [74]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(c1, axis=1)

array([0, 1, 0, 3, 0], dtype=int64)

In [75]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmin(c1, axis=0)

array([3, 4, 1, 2], dtype=int64)

In [79]:
# Create an array of normally distributed random numbers
d1 = np.random.normal(1,100)
d1

38.776959197309154

In [85]:
# Create an array with 10 evenly spaced numbers between 1 and 100
e1 = np.linspace(0, 100, 20, False)
e1

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75., 80., 85., 90., 95.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.